import { User, CheckIn } from "@/types";

export const users: User[] = [
  {
    id: "user-1",
    email: "nicko@employee.lifekeyshealth",
    password: "password123",
    name: "Nicko Balmes",
    role: "employee",
  },
  {
    id: "user-2",
    email: "lei@employee.lifekeyshealth",
    password: "password123",
    name: "Lei Shane Ezra",
    role: "employee",
  },
  {
    id: "user-3",
    email: "carol@employee.lifekeyshealth",
    password: "password123",
    name: "Carol Williams",
    role: "employee",
  },
  {
    id: "manager-1",
    email: "dave@manager.lifekeyshealth",
    password: "manager123",
    name: "Dave Manager",
    role: "manager",
  },
];

const daysAgo = (days: number, hour = 9): string => {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
};

export const checkIns: CheckIn[] = [
  {
    id: "ci-1",
    userId: "user-1",
    userName: "Nicko Balmes",
    mood: "Happy",
    rating: 4,
    note: "Great team meeting today!",
    createdAt: daysAgo(0),
  },
  {
    id: "ci-2",
    userId: "user-1",
    userName: "Nicko Balmes",
    mood: "Neutral",
    rating: 3,
    note: "Feeling okay, a bit tired.",
    createdAt: daysAgo(3),
  },
  {
    id: "ci-3",
    userId: "user-1",
    userName: "Nicko Balmes",
    mood: "Sad",
    rating: 2,
    note: "Rough day — lots of bugs to fix.",
    createdAt: daysAgo(7),
  },
  {
    id: "ci-4",
    userId: "user-1",
    userName: "Nicko Balmes",
    mood: "Excited",
    rating: 5,
    note: "Got promoted! Amazing news.",
    createdAt: daysAgo(14),
  },
  {
    id: "ci-5",
    userId: "user-1",
    userName: "Nicko Balmes",
    mood: "Happy",
    rating: 4,
    createdAt: daysAgo(21),
  },
  {
    id: "ci-6",
    userId: "user-2",
    userName: "Lei Shane Ezra",
    mood: "Excited",
    rating: 5,
    note: "New project kickoff — very energised!",
    createdAt: daysAgo(1),
  },
  {
    id: "ci-7",
    userId: "user-2",
    userName: "Lei Shane Ezra",
    mood: "Anxious",
    rating: 2,
    note: "Big deadline coming up next week.",
    createdAt: daysAgo(5),
  },
  {
    id: "ci-8",
    userId: "user-2",
    userName: "Lei Shane Ezra",
    mood: "Happy",
    rating: 4,
    createdAt: daysAgo(10),
  },
  {
    id: "ci-9",
    userId: "user-2",
    userName: "Lei Shane Ezra",
    mood: "Neutral",
    rating: 3,
    note: "Average week, nothing special.",
    createdAt: daysAgo(18),
  },
  {
    id: "ci-15",
    userId: "user-2",
    userName: "Lei Shane Ezra",
    mood: "Happy",
    rating: 5,
    note: "Team lunch was fantastic!",
    createdAt: daysAgo(25),
  },
  {
    id: "ci-10",
    userId: "user-3",
    userName: "Carol Williams",
    mood: "Happy",
    rating: 5,
    createdAt: daysAgo(2),
  },
  {
    id: "ci-11",
    userId: "user-3",
    userName: "Carol Williams",
    mood: "Neutral",
    rating: 3,
    note: "Just another Tuesday.",
    createdAt: daysAgo(6),
  },
  {
    id: "ci-12",
    userId: "user-3",
    userName: "Carol Williams",
    mood: "Sad",
    rating: 2,
    note: "Not feeling well today.",
    createdAt: daysAgo(9),
  },
  {
    id: "ci-13",
    userId: "user-3",
    userName: "Carol Williams",
    mood: "Excited",
    rating: 5,
    note: "Completed a major milestone!",
    createdAt: daysAgo(15),
  },
  {
    id: "ci-14",
    userId: "user-3",
    userName: "Carol Williams",
    mood: "Anxious",
    rating: 2,
    note: "Performance review week — nervous.",
    createdAt: daysAgo(22),
  },
];
